name: kitakatu
description: '飲み会をもっと楽しく'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  google_fonts: ^3.0.1
  pedantic_mono: ^1.18.0
  intl: ^0.17.0
  floating_action_bubble: ^1.1.4
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/json/

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/img/icon.png'
